server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/forumhub?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: forum
    password: forum
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true

springdoc:
  api-docs.enabled: true
  swagger-ui.path: /swagger
