CREATE TABLE users (
  id         BIGINT PRIMARY KEY AUTO_INCREMENT,
  name       VARCHAR(120)  NOT NULL,
  email      VARCHAR(160)  NOT NULL UNIQUE,
  password   VARCHAR(255)  NOT NULL,
  role       VARCHAR(30)   NOT NULL DEFAULT 'USER',
  created_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
